// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace Models.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130095835_LittleChanges")]
    partial class LittleChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FemaleFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FemaleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("FemaleLyceumName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FemalePurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FemaleTelegramUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaleFullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaleGroupId")
                        .HasColumnType("int");

                    b.Property<string>("MaleLyceumName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MalePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MalePurpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaleTelegramUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TelegramID")
                        .HasColumnType("bigint");

                    b.Property<int?>("fgroupId")
                        .HasColumnType("int");

                    b.Property<int?>("mgroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("fgroupId");

                    b.HasIndex("mgroupId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FemaleId")
                        .HasColumnType("int");

                    b.Property<int?>("MaleId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FemaleId");

                    b.HasIndex("MaleId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("Models.ModeService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ModeStatus")
                        .HasColumnType("int");

                    b.Property<long?>("TelegramId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("ModeServices");
                });

            modelBuilder.Entity("Models.TargetPartnerService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LastUserId")
                        .HasColumnType("int");

                    b.Property<long>("TelegramID")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TargetPartnerServices");
                });

            modelBuilder.Entity("Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupID")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TelegramID")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.UserRegistrationService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppStatus")
                        .HasColumnType("int");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserRegStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RegistrationStatuses");
                });

            modelBuilder.Entity("Models.Application", b =>
                {
                    b.HasOne("Models.Group", "fgroup")
                        .WithMany()
                        .HasForeignKey("fgroupId");

                    b.HasOne("Models.Group", "mgroup")
                        .WithMany()
                        .HasForeignKey("mgroupId");

                    b.Navigation("fgroup");

                    b.Navigation("mgroup");
                });

            modelBuilder.Entity("Models.Like", b =>
                {
                    b.HasOne("Models.UserProfile", "Female")
                        .WithMany()
                        .HasForeignKey("FemaleId");

                    b.HasOne("Models.UserProfile", "Male")
                        .WithMany()
                        .HasForeignKey("MaleId");

                    b.Navigation("Female");

                    b.Navigation("Male");
                });

            modelBuilder.Entity("Models.UserProfile", b =>
                {
                    b.HasOne("Models.Group", "group")
                        .WithMany("users")
                        .HasForeignKey("GroupID");

                    b.Navigation("group");
                });

            modelBuilder.Entity("Models.UserRegistrationService", b =>
                {
                    b.HasOne("Models.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Group", b =>
                {
                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
